# Generated by Django 4.2.5 on 2023-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
