# Generated by Django 4.2.5 on 2023-09-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_group',
            field=models.IntegerField(choices=[(2, 'kleine Gruppe'), (5, 'mittelgroße Gruppe'), (10, 'große Gruppe'), (0, 'ohne Limit')], default=0),
            preserve_default=False,
        ),
    ]
